export const OfficeTypes = {
  1: "virtual",
  2: "coworking",
  3: "private office",
  4: "meeting rooms",
};

export const OfficeSizes = {
  1: "individual",
  2: "small",
  3: "medium",
  4: "large",
};

export const PropertiesList = [
  {
    id: 1,
    address: "Beacon Hill, 100 Cambridge Street",
    dailyPrice: 10,
    type: OfficeTypes[2],
    size: OfficeSizes[1],
    city: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    image: "https://source.unsplash.com/400x600/?boston,building,office",
  },
  {
    id: 2,
    address: "Canal Street-North Station",
    dailyPrice: 8,
    type: OfficeTypes[3],
    size: OfficeSizes[2],
    city: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    image: "https://source.unsplash.com/400x600/?boston,building,office",
  },
  {
    id: 3,
    address: "101 Arch Street",
    dailyPrice: 9,
    type: OfficeTypes[3],
    size: OfficeSizes[2],
    city: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    image: "https://source.unsplash.com/400x600/?boston,building,office",
  },
  {
    id: 4,
    address: "100 Church Street",
    dailyPrice: 12,
    type: OfficeTypes[2],
    size: OfficeSizes[3],
    city: "New York City",
    state: "New York",
    stateCode: "NY",
    image: "https://source.unsplash.com/400x600/?new-york,building,office",
  },
  {
    id: 5,
    address: "One Liberty Plaza",
    dailyPrice: 11,
    type: OfficeTypes[3],
    size: OfficeSizes[1],
    city: "New York City",
    state: "New York",
    stateCode: "NY",
    image: "https://source.unsplash.com/400x600/?new-york,building,office",
  },
  {
    id: 6,
    address: "140 Broadway",
    dailyPrice: 9,
    type: OfficeTypes[3],
    size: OfficeSizes[1],
    city: "New York City",
    state: "New York",
    stateCode: "NY",
    image: "https://source.unsplash.com/400x600/?new-york,building,office",
  },
];
